[package]
name = "huginn"
version = "0.1.0"
authors = ["Alex PÃ©csi <alex.pecsi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "*"
actix-web = "1.*"
rand = "*"
serde = "*"
serde_yaml = "*"
